language: python

sudo: false

python:
  - "3.6"
  - "3.7"

service:
  - postgresql

addons:
  postgresql: "9.4"

env:
  - SECRET_KEY=supersecret DB_PORT=5432 DB_SERVICE=localhost DB_PASS="" DB_USER=postgres DB_NAME=postgres DJANGO_SETTINGS_MODULE=pyarweb.settings.development

install:
  - pip install pip -U
  - pip install -r dev_requirements.txt

script:
  - flake8
  - python3 manage.py test -v2 --noinput
