# Generated by Django 3.2.13 on 2022-07-14 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0015_alter_joboffer_company'),
        ('pycompanies', '0005_company_owner_to_usercompanyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
    ]
